import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import Sidenav from "@/components/Sidenav/Sidenav";
import Navbar from "@/components/Navbar/Navbar";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUIProvider>
      
       

          <section className="flex  ">
            <div className="w-[50px] hidden md:block ">
              <Sidenav />
            </div>
            <div className="flex-1">
              <Navbar />

              {children}
            </div>
          </section>

      


        </NextUIProvider>
      </body>
    </html>
  );
}
